
const courses =[
    {
        id:"1",
        image: require('../../assets/9.jpg'),
        title:"Web Development",
        description:"hey you al  of you amdn this id si is a decription and discription of the paragraph ofth  th worls oand fhdnnuqh dnhu ahudeb n uwiewwqd nsh akxaaa wdqwkw",
        course1:"HTML",
        course2:"CSS",
        course2:"JavaScript",
        price: 5000,
    },
    {
        id:"2",
        image: require('../../assets/9.jpg'),
        title:"Graphic Designing",
        description:"hey you al  of you amdn this id si is a decription and discription of the paragraph ofth  th worls oand fhdnnuqh dnhu ahudeb n uwiewwqd nsh akxaaa wdqwkw",
        course1:"Photoshop",
        course2:"Figma",
        course2:"Adobe XD",
        price: 3000,
    },
    {
        id:"3",
        image: require('../../assets/9.jpg'),
        title:"Coding Fundamentals",
        description:"hey you al  of you amdn this id si is a decription and discription of the paragraph ofth  th worls oand fhdnnuqh dnhu ahudeb n uwiewwqd nsh akxaaa wdqwkw",
        course1:"JavaScript",
        course2:"Algorithm",
        course2:"Data Structure",
        price: 1000,
    },
    {
        id:"4",
        image: require('../../assets/9.jpg'),
        title:"Ethical Hacking",
        description:"hey you al  of you amdn this id si is a decription and discription of the paragraph ofth  th worls oand fhdnnuqh dnhu ahudeb n uwiewwqd nsh akxaaa wdqwkw",
        course1:"Testing",
        course2:"Exploitation",
        course2:"Linux OS",
        price: 6000,
    },
    {
        id:"5",
        image: require('../../assets/9.jpg'),
        title:"",
        description:"hey you al  of you amdn this id si is a decription and discription of the paragraph ofth  th worls oand fhdnnuqh dnhu ahudeb n uwiewwqd nsh akxaaa wdqwkw",
        course1:"HTML",
        course2:"CSS",
        course2:"JavaScript",
        price: 5000,
    },
]
export default courses;